CREATE TABLE IF NOT EXISTS admin_audit_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trace_id VARCHAR(64),
  actor_id VARCHAR(64),
  actor_name VARCHAR(128),
  actor_role VARCHAR(32),
  village_id VARCHAR(64),
  module VARCHAR(64) NOT NULL,
  action VARCHAR(96) NOT NULL,
  target_type VARCHAR(64),
  target_id VARCHAR(128),
  request_method VARCHAR(16) NOT NULL,
  request_path VARCHAR(255) NOT NULL,
  client_ip VARCHAR(64),
  user_agent VARCHAR(512),
  result VARCHAR(16) NOT NULL,
  http_status INT NOT NULL,
  detail VARCHAR(512),
  before_data LONGTEXT,
  after_data LONGTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_created_at(created_at),
  INDEX idx_audit_actor(actor_id, created_at),
  INDEX idx_audit_module(module, created_at),
  INDEX idx_audit_result(result, created_at),
  INDEX idx_audit_trace(trace_id)
);
