spring:
  application:
    name: xiangyun-os-backend
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8088
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

logging:
  level:
    com.xiangyun.os: info
